baseURL = 'https://tying.us/'
languageCode = 'en-us'
title = 'tying.us'

theme = "reveal-hugo"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true
